rmdir Upperbay\Agent\BaseCell\bin /s /q
rmdir Upperbay\Agent\BaseCell\obj /s /q
rmdir Upperbay\Agent\Colony\bin /s /q
rmdir Upperbay\Agent\Colony\obj /s /q
rmdir Upperbay\Agent\ColonyMatrix\bin /s /q
rmdir Upperbay\Agent\ColonyMatrix\obj /s /q
rmdir Upperbay\Agent\ConfigurationSettings\bin /s /q
rmdir Upperbay\Agent\ConfigurationSettings\obj /s /q
rmdir Upperbay\Agent\Interfaces\bin /s /q
rmdir Upperbay\Agent\Interfaces\obj /s /q
rmdir Upperbay\AgentObjects\ClusterAgent\bin /s /q
rmdir Upperbay\AgentObjects\ClusterAgent\obj /s /q
rmdir Upperbay\AgentObjects\RainAgent\bin /s /q
rmdir Upperbay\AgentObjects\RainAgent\obj /s /q
rmdir Upperbay\AgentObjects\PowerAgent\bin /s /q
rmdir Upperbay\AgentObjects\PowerAgent\obj /s /q
rmdir Upperbay\AgentObjects\DataAgent\bin /s /q
rmdir Upperbay\AgentObjects\DataAgent\obj /s /q
rmdir Upperbay\AgentObjects\ModelAgent\bin /s /q
rmdir Upperbay\AgentObjects\ModelAgent\obj /s /q
rmdir Upperbay\Assistant\Cache\bin /s /q
rmdir Upperbay\Assistant\Cache\obj /s /q
rmdir Upperbay\Assistant\CloudMqttPublisher\bin /s /q
rmdir Upperbay\Assistant\CloudMqttPublisher\obj /s /q
rmdir Upperbay\Assistant\CloudMqttSecureSubscriber\bin /s /q
rmdir Upperbay\Assistant\CloudMqttSecureSubscriber\obj /s /q
rmdir Upperbay\Assistant\DaqDataAccessor\bin /s /q
rmdir Upperbay\Assistant\DaqDataAccessor\obj /s /q
rmdir Upperbay\Assistant\EtherReadAccessor\bin /s /q
rmdir Upperbay\Assistant\EtherReadAccessor\obj /s /q
rmdir Upperbay\Assistant\EtherWriteAccessor\bin /s /q
rmdir Upperbay\Assistant\EtherWriteAccessor\obj /s /q
rmdir Upperbay\Assistant\EventReactor\bin /s /q
rmdir Upperbay\Assistant\EventReactor\obj /s /q
rmdir Upperbay\Assistant\GameEventReactor\bin /s /q
rmdir Upperbay\Assistant\GameEventReactor\obj /s /q
rmdir Upperbay\Assistant\ManualInput\bin /s /q
rmdir Upperbay\Assistant\ManualInput\obj /s /q
rmdir Upperbay\Assistant\MqttPublisher\bin /s /q
rmdir Upperbay\Assistant\MqttPublisher\obj /s /q
rmdir Upperbay\Assistant\MqttSubscriber\bin /s /q
rmdir Upperbay\Assistant\MqttSubscriber\obj /s /q
rmdir Upperbay\Assistant\Simulator\bin /s /q
rmdir Upperbay\Assistant\Simulator\obj /s /q
rmdir Upperbay\Assistant\SmartThingsPublisher\bin /s /q
rmdir Upperbay\Assistant\SmartThingsPublisher\obj /s /q
rmdir Upperbay\Assistant\ThingSpeakReadAccessor\bin /s /q
rmdir Upperbay\Assistant\ThingSpeakReadAccessor\obj /s /q
rmdir Upperbay\Assistant\ThingSpeakWriteAccessor\bin /s /q
rmdir Upperbay\Assistant\ThingSpeakWriteAccessor\obj /s /q
rmdir Upperbay\Assistant\UaDataAccessor\bin /s /q
rmdir Upperbay\Assistant\UaDataAccessor\obj /s /q
rmdir Upperbay\Assistant\VariableProcessing\bin /s /q
rmdir Upperbay\Assistant\VariableProcessing\obj /s /q
rmdir Upperbay\Assistant\WeatherService\bin /s /q
rmdir Upperbay\Assistant\WeatherService\obj /s /q
rmdir Upperbay\Core\Library\bin /s /q
rmdir Upperbay\Core\Library\obj /s /q
rmdir Upperbay\Core\Logging\bin /s /q
rmdir Upperbay\Core\Logging\obj /s /q
rmdir Upperbay\Worker\AstronomyClock\bin /s /q
rmdir Upperbay\Worker\AstronomyClock\obj /s /q
rmdir Upperbay\Worker\Ears\bin /s /q
rmdir Upperbay\Worker\Ears\obj /s /q
rmdir Upperbay\Worker\EtherAccess\bin /s /q
rmdir Upperbay\Worker\EtherAccess\obj /s /q
rmdir Upperbay\Worker\Events\bin /s /q
rmdir Upperbay\Worker\Events\obj /s /q
rmdir Upperbay\Worker\Hasher\bin /s /q
rmdir Upperbay\Worker\Hasher\obj /s /q
rmdir Upperbay\Worker\JSON\bin /s /q
rmdir Upperbay\Worker\JSON\obj /s /q
rmdir Upperbay\Worker\LMP\bin /s /q
rmdir Upperbay\Worker\LMP\obj /s /q
rmdir Upperbay\Worker\MQTT\bin /s /q
rmdir Upperbay\Worker\MQTT\obj /s /q
rmdir Upperbay\Worker\ODBC\bin /s /q
rmdir Upperbay\Worker\ODBC\obj /s /q
rmdir Upperbay\Worker\PostOffice\bin /s /q
rmdir Upperbay\Worker\PostOffice\obj /s /q
rmdir Upperbay\Worker\ThingSpeak\bin /s /q
rmdir Upperbay\Worker\ThingSpeak\obj /s /q
rmdir Upperbay\Worker\Timers\bin /s /q
rmdir Upperbay\Worker\Timers\obj /s /q
rmdir Upperbay\Worker\Voice\bin /s /q
rmdir Upperbay\Worker\Voice\obj /s /q
rmdir Upperbay\Worker\VoiceCommands\bin /s /q
rmdir Upperbay\Worker\VoiceCommands\obj /s /q
rmdir Upperbay\Worker\XDocuments\bin /s /q
rmdir Upperbay\Worker\XDocuments\obj /s /q
